version: "3.9"

services:
  react-app:
    container_name: react_app
    image: react-boilerplate:latest   # <-- your image
    ports:
      - "80:80"                       # serve on port 80
    restart: always
